services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator
    restart: no
    environment:
      BASE_URL: localhost
      SECRET_KEY: test
      NETWORK_NAME: orchestrator
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  traefik:
    image: traefik:latest
    container_name: orchestrator-traefik
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "-entrypoints.http.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run/traefik:/traefik"
networks:
  default:
    name: orchestrator