services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orchestrator
    restart: no
    environment:
      BASE_URL: localhost
      SECRET_KEY: test
      NETWORK_NAME: orchestrator
      AUTHENTICATE: false
      DATABASE_PATH: /database.sqlite
      CONTAINER_LIFETIME: 1800
      PUBLIC_HOST: localhost
    ports:
      - "8000:8080"
    volumes:
      - "./run/database.sqlite:/database.sqlite"
      - "/var/run/docker.sock:/var/run/docker.sock"
  traefik:
    image: traefik:latest
    container_name: orchestrator-traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--providers.docker=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=5"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.tcp.address=:1000"
    ports:
      - "80:80"
      - "1000:1000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./run/traefik:/traefik"
      - "./run/acme:/acme"
networks:
  default:
    name: orchestrator